// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: virtio_gpu_ring_blob_snapshot.proto
// Protobuf C++ Version: 7.36.1

#ifndef virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto_2epb_2eh
#define virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7036001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto;
}  // extern "C"
namespace gfxstream {
namespace host {
namespace snapshot {
enum VirtioGpuRingBlobSnapshot_Type : int;
extern const uint32_t VirtioGpuRingBlobSnapshot_Type_internal_data_[];
class VirtioGpuRingBlobSnapshot;
struct VirtioGpuRingBlobSnapshotGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern VirtioGpuRingBlobSnapshotGlobalsTypeInternal VirtioGpuRingBlobSnapshot_globals_;
extern const ::google::protobuf::internal::ClassDataFull VirtioGpuRingBlobSnapshot_class_data_;
#else
extern const VirtioGpuRingBlobSnapshotGlobalsTypeInternal VirtioGpuRingBlobSnapshot_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace snapshot
}  // namespace host
}  // namespace gfxstream
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot_Type_internal_data_>
    internal::EnumTraitsImpl::value<::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot_Type>;
}  // namespace protobuf
}  // namespace google

namespace gfxstream {
namespace host {
namespace snapshot {
enum VirtioGpuRingBlobSnapshot_Type : int {
  VirtioGpuRingBlobSnapshot_Type_TYPE_HOST_MEMORY = 0,
  VirtioGpuRingBlobSnapshot_Type_TYPE_SHARED_MEMORY = 1,
  VirtioGpuRingBlobSnapshot_Type_VirtioGpuRingBlobSnapshot_Type_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  VirtioGpuRingBlobSnapshot_Type_VirtioGpuRingBlobSnapshot_Type_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t VirtioGpuRingBlobSnapshot_Type_internal_data_[];
inline constexpr VirtioGpuRingBlobSnapshot_Type VirtioGpuRingBlobSnapshot_Type_Type_MIN =
    static_cast<VirtioGpuRingBlobSnapshot_Type>(0);
inline constexpr VirtioGpuRingBlobSnapshot_Type VirtioGpuRingBlobSnapshot_Type_Type_MAX =
    static_cast<VirtioGpuRingBlobSnapshot_Type>(1);
[[nodiscard]] inline bool VirtioGpuRingBlobSnapshot_Type_IsValid(int value) {
  return 0 <= value && value <= 1;
}
inline constexpr int VirtioGpuRingBlobSnapshot_Type_Type_ARRAYSIZE = 1 + 1;
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
VirtioGpuRingBlobSnapshot_Type_descriptor();
[[nodiscard]] inline auto ProtobufInternalGetEnumDescriptor(VirtioGpuRingBlobSnapshot_Type) {
  return VirtioGpuRingBlobSnapshot_Type_descriptor();
}
template <typename T>
[[nodiscard]] const ::std::string& VirtioGpuRingBlobSnapshot_Type_Name(T value) {
  static_assert(::std::is_same<T, VirtioGpuRingBlobSnapshot_Type>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Type_Name().");
  return VirtioGpuRingBlobSnapshot_Type_Name(static_cast<VirtioGpuRingBlobSnapshot_Type>(value));
}
template <>
[[nodiscard]] inline const ::std::string& VirtioGpuRingBlobSnapshot_Type_Name(VirtioGpuRingBlobSnapshot_Type value) {
  return ::google::protobuf::internal::NameOfDenseEnum<VirtioGpuRingBlobSnapshot_Type_descriptor, 0, 1>(
      static_cast<int>(value));
}
[[nodiscard]] inline bool VirtioGpuRingBlobSnapshot_Type_Parse(
    ::absl::string_view name, VirtioGpuRingBlobSnapshot_Type* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<VirtioGpuRingBlobSnapshot_Type>(VirtioGpuRingBlobSnapshot_Type_descriptor(), name,
                                           value);
}
using ::google::protobuf::internal::generated_enum::AbslParseFlag;
using ::google::protobuf::internal::generated_enum::AbslUnparseFlag;

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED VirtioGpuRingBlobSnapshot final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot) */ {
  using Super_ = ::google::protobuf::Message;

 public:
  inline VirtioGpuRingBlobSnapshot() : VirtioGpuRingBlobSnapshot(nullptr) {}
  ~VirtioGpuRingBlobSnapshot() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(VirtioGpuRingBlobSnapshot* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(VirtioGpuRingBlobSnapshot));
  }
#endif

  template <typename = void>
  explicit constexpr VirtioGpuRingBlobSnapshot(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline VirtioGpuRingBlobSnapshot(const VirtioGpuRingBlobSnapshot& from) : VirtioGpuRingBlobSnapshot(nullptr, from) {}
  inline VirtioGpuRingBlobSnapshot(VirtioGpuRingBlobSnapshot&& from) noexcept : VirtioGpuRingBlobSnapshot(nullptr, ::std::move(from)) {}
  inline VirtioGpuRingBlobSnapshot& operator=(const VirtioGpuRingBlobSnapshot& from) {
    CopyFrom(from);
    return *this;
  }
  inline VirtioGpuRingBlobSnapshot& operator=(VirtioGpuRingBlobSnapshot&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const VirtioGpuRingBlobSnapshot& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<VirtioGpuRingBlobSnapshot>(&VirtioGpuRingBlobSnapshot_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(VirtioGpuRingBlobSnapshot& a, VirtioGpuRingBlobSnapshot& b) { a.Swap(&b); }
  inline void Swap(VirtioGpuRingBlobSnapshot* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VirtioGpuRingBlobSnapshot* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] VirtioGpuRingBlobSnapshot* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return Super_::DefaultConstruct<VirtioGpuRingBlobSnapshot>(arena);
  }
  using Super_::CopyFrom;
  void CopyFrom(const VirtioGpuRingBlobSnapshot& from);
  using Super_::MergeFrom;
  void MergeFrom(const VirtioGpuRingBlobSnapshot& from) { VirtioGpuRingBlobSnapshot::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(VirtioGpuRingBlobSnapshot* PROTOBUF_NONNULL other);
 private:
  static ::absl::string_view FullMessageName() { return "gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot"; }

  explicit VirtioGpuRingBlobSnapshot(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  VirtioGpuRingBlobSnapshot(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const VirtioGpuRingBlobSnapshot& from);
  VirtioGpuRingBlobSnapshot(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, VirtioGpuRingBlobSnapshot&& from) noexcept
      : VirtioGpuRingBlobSnapshot(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Type = VirtioGpuRingBlobSnapshot_Type;
  static constexpr Type TYPE_HOST_MEMORY = VirtioGpuRingBlobSnapshot_Type_TYPE_HOST_MEMORY;
  static constexpr Type TYPE_SHARED_MEMORY = VirtioGpuRingBlobSnapshot_Type_TYPE_SHARED_MEMORY;
  [[nodiscard]] static inline bool Type_IsValid(int value) {
    return VirtioGpuRingBlobSnapshot_Type_IsValid(value);
  }
  static constexpr Type Type_MIN = VirtioGpuRingBlobSnapshot_Type_Type_MIN;
  static constexpr Type Type_MAX = VirtioGpuRingBlobSnapshot_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE = VirtioGpuRingBlobSnapshot_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Type_descriptor() {
    return VirtioGpuRingBlobSnapshot_Type_descriptor();
  }
  template <typename T>
  [[nodiscard]] static inline const ::std::string& Type_Name(T value) {
    return VirtioGpuRingBlobSnapshot_Type_Name(value);
  }
  [[nodiscard]] static inline bool Type_Parse(
      ::absl::string_view name, Type* PROTOBUF_NONNULL value) {
    return VirtioGpuRingBlobSnapshot_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kMemoryFieldNumber = 5,
    kSizeFieldNumber = 2,
    kIdFieldNumber = 1,
    kTypeFieldNumber = 4,
    kAlignmentFieldNumber = 3,
  };
  // bytes memory = 5;
  void clear_memory() ;
  [[nodiscard]] const ::std::string& memory() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_memory(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_memory();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_memory();
  void set_allocated_memory(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_memory() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_memory(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_memory();

  public:
  // uint64 size = 2;
  void clear_size() ;
  [[nodiscard]] ::uint64_t size() const;
  void set_size(::uint64_t value);

  private:
  ::uint64_t _internal_size() const;
  void _internal_set_size(::uint64_t value);

  public:
  // uint32 id = 1;
  void clear_id() ;
  [[nodiscard]] ::uint32_t id() const;
  void set_id(::uint32_t value);

  private:
  ::uint32_t _internal_id() const;
  void _internal_set_id(::uint32_t value);

  public:
  // .gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot.Type type = 4;
  void clear_type() ;
  [[nodiscard]] ::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot_Type type() const;
  void set_type(::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot_Type value);

  private:
  ::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot_Type _internal_type() const;
  void _internal_set_type(::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot_Type value);

  public:
  // uint64 alignment = 3;
  void clear_alignment() ;
  [[nodiscard]] ::uint64_t alignment() const;
  void set_alignment(::uint64_t value);

  private:
  ::uint64_t _internal_alignment() const;
  void _internal_set_alignment(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<3, 5,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const VirtioGpuRingBlobSnapshot& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr memory_;
    ::uint64_t size_;
    ::uint32_t id_;
    int type_;
    ::uint64_t alignment_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// VirtioGpuRingBlobSnapshot

// uint32 id = 1;
inline void VirtioGpuRingBlobSnapshot::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline ::uint32_t VirtioGpuRingBlobSnapshot::id() const {
  // @@protoc_insertion_point(field_get:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot.id)
  return _internal_id();
}
inline void VirtioGpuRingBlobSnapshot::set_id(::uint32_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot.id)
}
inline ::uint32_t VirtioGpuRingBlobSnapshot::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void VirtioGpuRingBlobSnapshot::_internal_set_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// uint64 size = 2;
inline void VirtioGpuRingBlobSnapshot::clear_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.size_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline ::uint64_t VirtioGpuRingBlobSnapshot::size() const {
  // @@protoc_insertion_point(field_get:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot.size)
  return _internal_size();
}
inline void VirtioGpuRingBlobSnapshot::set_size(::uint64_t value) {
  _internal_set_size(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot.size)
}
inline ::uint64_t VirtioGpuRingBlobSnapshot::_internal_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.size_;
}
inline void VirtioGpuRingBlobSnapshot::_internal_set_size(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.size_ = value;
}

// uint64 alignment = 3;
inline void VirtioGpuRingBlobSnapshot::clear_alignment() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.alignment_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
}
inline ::uint64_t VirtioGpuRingBlobSnapshot::alignment() const {
  // @@protoc_insertion_point(field_get:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot.alignment)
  return _internal_alignment();
}
inline void VirtioGpuRingBlobSnapshot::set_alignment(::uint64_t value) {
  _internal_set_alignment(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot.alignment)
}
inline ::uint64_t VirtioGpuRingBlobSnapshot::_internal_alignment() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.alignment_;
}
inline void VirtioGpuRingBlobSnapshot::_internal_set_alignment(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.alignment_ = value;
}

// .gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot.Type type = 4;
inline void VirtioGpuRingBlobSnapshot::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline ::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot_Type VirtioGpuRingBlobSnapshot::type() const {
  // @@protoc_insertion_point(field_get:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot.type)
  return _internal_type();
}
inline void VirtioGpuRingBlobSnapshot::set_type(::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot_Type value) {
  _internal_set_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot.type)
}
inline ::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot_Type VirtioGpuRingBlobSnapshot::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot_Type>(_impl_.type_);
}
inline void VirtioGpuRingBlobSnapshot::_internal_set_type(::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot_Type value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// bytes memory = 5;
inline void VirtioGpuRingBlobSnapshot::clear_memory() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.memory_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& VirtioGpuRingBlobSnapshot::memory() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot.memory)
  return _internal_memory();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void VirtioGpuRingBlobSnapshot::set_memory(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.memory_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot.memory)
}
inline ::std::string* PROTOBUF_NONNULL VirtioGpuRingBlobSnapshot::mutable_memory()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_memory();
  // @@protoc_insertion_point(field_mutable:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot.memory)
  return _s;
}
inline const ::std::string& VirtioGpuRingBlobSnapshot::_internal_memory() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.memory_.Get();
}
inline void VirtioGpuRingBlobSnapshot::_internal_set_memory(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.memory_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL VirtioGpuRingBlobSnapshot::_internal_mutable_memory() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.memory_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE VirtioGpuRingBlobSnapshot::release_memory() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot.memory)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.memory_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.memory_.Set("", GetArena());
  }
  return released;
}
inline void VirtioGpuRingBlobSnapshot::set_allocated_memory(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.memory_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.memory_.IsDefault()) {
    _impl_.memory_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot.memory)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace snapshot
}  // namespace host
}  // namespace gfxstream


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot_Type> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot_Type>() {
  return ::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto_2epb_2eh
