// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: virtio_gpu_ring_blob_snapshot.proto
// Protobuf C++ Version: 7.36.1

#include "virtio_gpu_ring_blob_snapshot.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot
        {&::_pbi::kDescriptorMethods, &::descriptor_table_virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
namespace gfxstream {
namespace host {
namespace snapshot {
class VirtioGpuRingBlobSnapshot::_Internal {
 public:
  using HasBits = decltype(::std::declval<VirtioGpuRingBlobSnapshot>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(VirtioGpuRingBlobSnapshot, _impl_._has_bits_);
};

constexpr VirtioGpuRingBlobSnapshot::ParseTableT_ VirtioGpuRingBlobSnapshot::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(VirtioGpuRingBlobSnapshot, _impl_._has_bits_),
      0, // no _extensions_
      5, 56,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967264,  // skipmap
      offsetof(ParseTableT_, field_entries),
      5,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::MpUnknownFields,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // uint32 id = 1;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VirtioGpuRingBlobSnapshot, _impl_.id_), 2>(),
       {8, 2, 0,
        PROTOBUF_FIELD_OFFSET(VirtioGpuRingBlobSnapshot, _impl_.id_)}},
      // uint64 size = 2;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(VirtioGpuRingBlobSnapshot, _impl_.size_), 1>(),
       {16, 1, 0,
        PROTOBUF_FIELD_OFFSET(VirtioGpuRingBlobSnapshot, _impl_.size_)}},
      // uint64 alignment = 3;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(VirtioGpuRingBlobSnapshot, _impl_.alignment_), 4>(),
       {24, 4, 0,
        PROTOBUF_FIELD_OFFSET(VirtioGpuRingBlobSnapshot, _impl_.alignment_)}},
      // .gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot.Type type = 4;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VirtioGpuRingBlobSnapshot, _impl_.type_), 3>(),
       {32, 3, 0,
        PROTOBUF_FIELD_OFFSET(VirtioGpuRingBlobSnapshot, _impl_.type_)}},
      // bytes memory = 5;
      {::_pbi::TcParser::FastBS1,
       {42, 0, 0,
        PROTOBUF_FIELD_OFFSET(VirtioGpuRingBlobSnapshot, _impl_.memory_)}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, {{
      // uint32 id = 1;
      {PROTOBUF_FIELD_OFFSET(VirtioGpuRingBlobSnapshot, _impl_.id_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // uint64 size = 2;
      {PROTOBUF_FIELD_OFFSET(VirtioGpuRingBlobSnapshot, _impl_.size_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
      // uint64 alignment = 3;
      {PROTOBUF_FIELD_OFFSET(VirtioGpuRingBlobSnapshot, _impl_.alignment_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
      // .gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot.Type type = 4;
      {PROTOBUF_FIELD_OFFSET(VirtioGpuRingBlobSnapshot, _impl_.type_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
      // bytes memory = 5;
      {PROTOBUF_FIELD_OFFSET(VirtioGpuRingBlobSnapshot, _impl_.memory_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    }},
    // no aux_entries
    {{
    }},
  };
}


inline constexpr VirtioGpuRingBlobSnapshot::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : memory_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        size_{::uint64_t{0u}},
        id_{0u},
        type_{static_cast< ::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot_Type >(0)},
        alignment_{::uint64_t{0u}} {}

template <typename>
constexpr VirtioGpuRingBlobSnapshot::VirtioGpuRingBlobSnapshot(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL VirtioGpuRingBlobSnapshot::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) VirtioGpuRingBlobSnapshot(arena);
}
constexpr auto VirtioGpuRingBlobSnapshot::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(VirtioGpuRingBlobSnapshot), alignof(VirtioGpuRingBlobSnapshot));
}
constexpr auto VirtioGpuRingBlobSnapshot::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &VirtioGpuRingBlobSnapshot::MergeImpl,
          Super_::GetNewImpl<VirtioGpuRingBlobSnapshot>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &VirtioGpuRingBlobSnapshot::SharedDtor,
          Super_::GetClearImpl<VirtioGpuRingBlobSnapshot>(), &VirtioGpuRingBlobSnapshot::ByteSizeLong,
              &VirtioGpuRingBlobSnapshot::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(VirtioGpuRingBlobSnapshot, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct VirtioGpuRingBlobSnapshotGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr VirtioGpuRingBlobSnapshotGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 VirtioGpuRingBlobSnapshot_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(VirtioGpuRingBlobSnapshot::InternalGenerateClassData_(
            _default, &VirtioGpuRingBlobSnapshot_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<VirtioGpuRingBlobSnapshot>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~VirtioGpuRingBlobSnapshotGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) VirtioGpuRingBlobSnapshot _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<VirtioGpuRingBlobSnapshot>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(VirtioGpuRingBlobSnapshotGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST VirtioGpuRingBlobSnapshotGlobalsTypeInternal VirtioGpuRingBlobSnapshot_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* VirtioGpuRingBlobSnapshot_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return VirtioGpuRingBlobSnapshot_globals_.GetClassData();
#else
  return VirtioGpuRingBlobSnapshot_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace snapshot
}  // namespace host
}  // namespace gfxstream
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto = nullptr;
const ::uint32_t
    TableStruct_virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot, _impl_.size_),
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot, _impl_.alignment_),
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot, _impl_.memory_),
        2,
        1,
        4,
        3,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot_globals_,
};
const char descriptor_table_protodef_virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n#virtio_gpu_ring_blob_snapshot.proto\022\027g"
    "fxstream.host.snapshot\"\325\001\n\031VirtioGpuRing"
    "BlobSnapshot\022\n\n\002id\030\001 \001(\r\022\014\n\004size\030\002 \001(\004\022\021"
    "\n\talignment\030\003 \001(\004\022E\n\004type\030\004 \001(\01627.gfxstr"
    "eam.host.snapshot.VirtioGpuRingBlobSnaps"
    "hot.Type\022\016\n\006memory\030\005 \001(\014\"4\n\004Type\022\024\n\020TYPE"
    "_HOST_MEMORY\020\000\022\026\n\022TYPE_SHARED_MEMORY\020\001b\006"
    "proto3"
};
static ::absl::once_flag descriptor_table_virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto = {
    false,
    false,
    286,
    descriptor_table_protodef_virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto,
    "virtio_gpu_ring_blob_snapshot.proto",
    &descriptor_table_virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_message_globals,
    TableStruct_virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto::offsets,
    file_level_enum_descriptors_virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto,
    file_level_service_descriptors_virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto,
};
namespace gfxstream {
namespace host {
namespace snapshot {
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
VirtioGpuRingBlobSnapshot_Type_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto);
  return file_level_enum_descriptors_virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t VirtioGpuRingBlobSnapshot_Type_internal_data_[] = {
    131072u, 0u, };
// ===================================================================

VirtioGpuRingBlobSnapshot::VirtioGpuRingBlobSnapshot(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, VirtioGpuRingBlobSnapshot_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot)
}
PROTOBUF_NDEBUG_INLINE VirtioGpuRingBlobSnapshot::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::gfxstream::host::snapshot::VirtioGpuRingBlobSnapshot& from_msg)
      : _has_bits_{from._has_bits_},
        memory_(arena, from.memory_) {}

VirtioGpuRingBlobSnapshot::VirtioGpuRingBlobSnapshot(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const VirtioGpuRingBlobSnapshot& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, VirtioGpuRingBlobSnapshot_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  VirtioGpuRingBlobSnapshot* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, size_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, size_),
           offsetof(Impl_, alignment_) -
               offsetof(Impl_, size_) +
               sizeof(Impl_::alignment_));

  // @@protoc_insertion_point(copy_constructor:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot)
}
PROTOBUF_NDEBUG_INLINE VirtioGpuRingBlobSnapshot::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : memory_(arena) {}

inline void VirtioGpuRingBlobSnapshot::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, size_),
           0,
           offsetof(Impl_, alignment_) -
               offsetof(Impl_, size_) +
               sizeof(Impl_::alignment_));
}
VirtioGpuRingBlobSnapshot::~VirtioGpuRingBlobSnapshot() {
  // @@protoc_insertion_point(destructor:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot)
  SharedDtor(*this);
}
inline void VirtioGpuRingBlobSnapshot::SharedDtor(MessageLite& self) {
  VirtioGpuRingBlobSnapshot& this_ = static_cast<VirtioGpuRingBlobSnapshot&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.memory_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull VirtioGpuRingBlobSnapshot_class_data_ =
        VirtioGpuRingBlobSnapshot::InternalGenerateClassData_(VirtioGpuRingBlobSnapshot_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VirtioGpuRingBlobSnapshot::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&VirtioGpuRingBlobSnapshot_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(VirtioGpuRingBlobSnapshot_class_data_.tc_table);
  return VirtioGpuRingBlobSnapshot_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VirtioGpuRingBlobSnapshot::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&VirtioGpuRingBlobSnapshot_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&VirtioGpuRingBlobSnapshot_globals_));
  return VirtioGpuRingBlobSnapshot_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const VirtioGpuRingBlobSnapshot::ParseTableT_
    VirtioGpuRingBlobSnapshot::_table_ =
        VirtioGpuRingBlobSnapshot::InternalGenerateParseTable_(VirtioGpuRingBlobSnapshot_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void VirtioGpuRingBlobSnapshot::Clear() {
  auto& this_ [[maybe_unused]] = *this;
  // @@protoc_insertion_point(message_clear_start:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  cached_has_bits = this_._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    this_._impl_.memory_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000001eU)) {
    ::memset(&this_._impl_.size_, 0,
             static_cast<::size_t>(
                 reinterpret_cast<char*>(&this_._impl_.alignment_) -
                 reinterpret_cast<char*>(&this_._impl_.size_)) +
                 sizeof(_impl_.alignment_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL VirtioGpuRingBlobSnapshot::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const VirtioGpuRingBlobSnapshot& this_ = static_cast<const VirtioGpuRingBlobSnapshot&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL VirtioGpuRingBlobSnapshot::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const VirtioGpuRingBlobSnapshot& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint32 id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_id(), target);
    }
  }

  // uint64 size = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_size() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          2, this_._internal_size(), target);
    }
  }

  // uint64 alignment = 3;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_alignment() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          3, this_._internal_alignment(), target);
    }
  }

  // .gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot.Type type = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          4, this_._internal_type(), target);
    }
  }

  // bytes memory = 5;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_memory().empty()) {
      const ::std::string& _s = this_._internal_memory();
      target = stream->WriteBytesMaybeAliased(5, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t VirtioGpuRingBlobSnapshot::ByteSizeLong(const MessageLite& base) {
  const VirtioGpuRingBlobSnapshot& this_ = static_cast<const VirtioGpuRingBlobSnapshot&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t VirtioGpuRingBlobSnapshot::ByteSizeLong() const {
  const VirtioGpuRingBlobSnapshot& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // bytes memory = 5;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_memory().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_memory());
      }
    }
    // uint64 size = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_size() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_size());
      }
    }
    // uint32 id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_id());
      }
    }
    // .gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot.Type type = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
      }
    }
    // uint64 alignment = 3;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_alignment() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_alignment());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void VirtioGpuRingBlobSnapshot::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<VirtioGpuRingBlobSnapshot*>(&to_msg);
  auto& from = static_cast<const VirtioGpuRingBlobSnapshot&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_memory().empty()) {
        _this->_internal_set_memory(from._internal_memory());
      } else {
        if (_this->_impl_.memory_.IsDefault()) {
          _this->_internal_set_memory("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_size() != 0) {
        _this->_impl_.size_ = from._impl_.size_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_type() != 0) {
        _this->_impl_.type_ = from._impl_.type_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_alignment() != 0) {
        _this->_impl_.alignment_ = from._impl_.alignment_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void VirtioGpuRingBlobSnapshot::CopyFrom(const VirtioGpuRingBlobSnapshot& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:gfxstream.host.snapshot.VirtioGpuRingBlobSnapshot)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void VirtioGpuRingBlobSnapshot::InternalSwap(VirtioGpuRingBlobSnapshot* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.memory_, &other->_impl_.memory_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VirtioGpuRingBlobSnapshot, _impl_.alignment_)
      + sizeof(VirtioGpuRingBlobSnapshot::_impl_.alignment_)
      - PROTOBUF_FIELD_OFFSET(VirtioGpuRingBlobSnapshot, _impl_.size_)>(
          reinterpret_cast<char*>(&_impl_.size_),
          reinterpret_cast<char*>(&other->_impl_.size_));
}

::google::protobuf::Metadata VirtioGpuRingBlobSnapshot::GetMetadata() const {
  return Super_::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace snapshot
}  // namespace host
}  // namespace gfxstream
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_virtio_5fgpu_5fring_5fblob_5fsnapshot_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
