// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: virtio_gpu_frontend_snapshot.proto
// Protobuf C++ Version: 7.36.1

#include "virtio_gpu_frontend_snapshot.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse
        {&::_pbi::kDescriptorMethods, &::descriptor_table_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto, /* tracker*/ nullptr,},
        // ::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse
        {&::_pbi::kDescriptorMethods, &::descriptor_table_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto, /* tracker*/ nullptr,},
        // ::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot
        {&::_pbi::kDescriptorMethods, &::descriptor_table_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
namespace gfxstream {
namespace host {
namespace snapshot {
constexpr VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse::ParseTableT_ VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse, _impl_._has_bits_),
      0, // no _extensions_
      2, 8,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967292,  // skipmap
      offsetof(ParseTableT_, field_entries),
      2,  // num_field_entries
      1,  // num_aux_entries
      offsetof(ParseTableT_, aux_entries),
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // .gfxstream.host.snapshot.VirtioGpuResourceSnapshot value = 2;
      {::_pbi::TcParser::FastMtS1,
       {18, 0, 0,
        PROTOBUF_FIELD_OFFSET(VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse, _impl_.value_)}},
      // uint32 key = 1;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse, _impl_.key_), 1>(),
       {8, 1, 0,
        PROTOBUF_FIELD_OFFSET(VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse, _impl_.key_)}},
    }}, {{
      65535, 65535
    }}, {{
      // uint32 key = 1;
      {PROTOBUF_FIELD_OFFSET(VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // .gfxstream.host.snapshot.VirtioGpuResourceSnapshot value = 2;
      {PROTOBUF_FIELD_OFFSET(VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    }},
    {{
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::gfxstream::host::snapshot::VirtioGpuResourceSnapshot>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::gfxstream::host::snapshot::VirtioGpuResourceSnapshot_globals_},
        #endif
    }},
    {{
    }},
  };
}

template <typename>
constexpr VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse::VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
      ) {
}
inline void* PROTOBUF_NONNULL VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse(arena);
}
constexpr auto VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse), alignof(VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse));
}
constexpr auto VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse::MergeImpl,
          Super_::GetNewImpl<VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse::ClearImpl),
              Super_::ByteSizeLongImpl, Super_::_InternalSerializeImpl,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[1],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUseGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUseGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse::InternalGenerateClassData_(
            _default, &VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUseGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUseGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUseGlobalsTypeInternal VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse_globals_.GetClassData();
#else
  return VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
constexpr VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse::ParseTableT_ VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse, _impl_._has_bits_),
      0, // no _extensions_
      2, 8,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967292,  // skipmap
      offsetof(ParseTableT_, field_entries),
      2,  // num_field_entries
      1,  // num_aux_entries
      offsetof(ParseTableT_, aux_entries),
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // .gfxstream.host.snapshot.VirtioGpuContextSnapshot value = 2;
      {::_pbi::TcParser::FastMtS1,
       {18, 0, 0,
        PROTOBUF_FIELD_OFFSET(VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse, _impl_.value_)}},
      // uint32 key = 1;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse, _impl_.key_), 1>(),
       {8, 1, 0,
        PROTOBUF_FIELD_OFFSET(VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse, _impl_.key_)}},
    }}, {{
      65535, 65535
    }}, {{
      // uint32 key = 1;
      {PROTOBUF_FIELD_OFFSET(VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // .gfxstream.host.snapshot.VirtioGpuContextSnapshot value = 2;
      {PROTOBUF_FIELD_OFFSET(VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    }},
    {{
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::gfxstream::host::snapshot::VirtioGpuContextSnapshot>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::gfxstream::host::snapshot::VirtioGpuContextSnapshot_globals_},
        #endif
    }},
    {{
    }},
  };
}

template <typename>
constexpr VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse::VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
      ) {
}
inline void* PROTOBUF_NONNULL VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse(arena);
}
constexpr auto VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse), alignof(VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse));
}
constexpr auto VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse::MergeImpl,
          Super_::GetNewImpl<VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse::ClearImpl),
              Super_::ByteSizeLongImpl, Super_::_InternalSerializeImpl,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUseGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUseGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse::InternalGenerateClassData_(
            _default, &VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUseGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUseGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUseGlobalsTypeInternal VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse_globals_.GetClassData();
#else
  return VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class VirtioGpuFrontendSnapshot::_Internal {
 public:
  using HasBits = decltype(::std::declval<VirtioGpuFrontendSnapshot>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(VirtioGpuFrontendSnapshot, _impl_._has_bits_);
};

constexpr VirtioGpuFrontendSnapshot::ParseTableT_ VirtioGpuFrontendSnapshot::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(VirtioGpuFrontendSnapshot, _impl_._has_bits_),
      0, // no _extensions_
      3, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967288,  // skipmap
      offsetof(ParseTableT_, field_entries),
      3,  // num_field_entries
      5,  // num_aux_entries
      offsetof(ParseTableT_, aux_entries),
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::MpUnknownFields,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // optional .gfxstream.host.snapshot.VirtioGpuTimelinesSnapshot timelines = 3;
      {::_pbi::TcParser::FastMtS1,
       {26, 0, 0,
        PROTOBUF_FIELD_OFFSET(VirtioGpuFrontendSnapshot, _impl_.timelines_)}},
    }}, {{
      65535, 65535
    }}, {{
      // map<uint32, .gfxstream.host.snapshot.VirtioGpuContextSnapshot> contexts = 1;
      {PROTOBUF_FIELD_OFFSET(VirtioGpuFrontendSnapshot, _impl_.contexts_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
      // map<uint32, .gfxstream.host.snapshot.VirtioGpuResourceSnapshot> resources = 2;
      {PROTOBUF_FIELD_OFFSET(VirtioGpuFrontendSnapshot, _impl_.resources_), _Internal::kHasBitsOffset + 2, 3, (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
      // optional .gfxstream.host.snapshot.VirtioGpuTimelinesSnapshot timelines = 3;
      {PROTOBUF_FIELD_OFFSET(VirtioGpuFrontendSnapshot, _impl_.timelines_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    }},
    {{
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot_globals_},
        #endif
        {::_pbi::TcParser::GetMapAuxInfo(
            0, 0, 13, 11, 0)},
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::gfxstream::host::snapshot::VirtioGpuContextSnapshot>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::gfxstream::host::snapshot::VirtioGpuContextSnapshot_globals_},
        #endif
        {::_pbi::TcParser::GetMapAuxInfo(
            0, 0, 13, 11, 0)},
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::gfxstream::host::snapshot::VirtioGpuResourceSnapshot>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::gfxstream::host::snapshot::VirtioGpuResourceSnapshot_globals_},
        #endif
    }},
    {{
    }},
  };
}


inline constexpr VirtioGpuFrontendSnapshot::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : timelines_{nullptr},
        contexts_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot,
            PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot, _impl_.contexts_)>()
         }
        ,
        resources_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot,
            PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot, _impl_.resources_)>()
         }
     {}

template <typename>
constexpr VirtioGpuFrontendSnapshot::VirtioGpuFrontendSnapshot(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL VirtioGpuFrontendSnapshot::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) VirtioGpuFrontendSnapshot(arena);
}
constexpr auto VirtioGpuFrontendSnapshot::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(VirtioGpuFrontendSnapshot), alignof(VirtioGpuFrontendSnapshot));
}
constexpr auto VirtioGpuFrontendSnapshot::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &VirtioGpuFrontendSnapshot::MergeImpl,
          Super_::GetNewImpl<VirtioGpuFrontendSnapshot>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &VirtioGpuFrontendSnapshot::SharedDtor,
          Super_::GetClearImpl<VirtioGpuFrontendSnapshot>(), &VirtioGpuFrontendSnapshot::ByteSizeLong,
              &VirtioGpuFrontendSnapshot::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(VirtioGpuFrontendSnapshot, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[2],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct VirtioGpuFrontendSnapshotGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr VirtioGpuFrontendSnapshotGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 VirtioGpuFrontendSnapshot_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(VirtioGpuFrontendSnapshot::InternalGenerateClassData_(
            _default, &VirtioGpuFrontendSnapshot_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<VirtioGpuFrontendSnapshot>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~VirtioGpuFrontendSnapshotGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) VirtioGpuFrontendSnapshot _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<VirtioGpuFrontendSnapshot>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(VirtioGpuFrontendSnapshotGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST VirtioGpuFrontendSnapshotGlobalsTypeInternal VirtioGpuFrontendSnapshot_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* VirtioGpuFrontendSnapshot_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return VirtioGpuFrontendSnapshot_globals_.GetClassData();
#else
  return VirtioGpuFrontendSnapshot_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace snapshot
}  // namespace host
}  // namespace gfxstream
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto = nullptr;
const ::uint32_t
    TableStruct_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse, _impl_.value_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse, _impl_.value_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot, _impl_.contexts_),
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot, _impl_.resources_),
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot, _impl_.timelines_),
        1,
        2,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse)},
        {7, sizeof(::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse)},
        {14, sizeof(::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse_globals_,
        &::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse_globals_,
        &::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot_globals_,
};
const char descriptor_table_protodef_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\"virtio_gpu_frontend_snapshot.proto\022\027gf"
    "xstream.host.snapshot\032!virtio_gpu_contex"
    "t_snapshot.proto\032\"virtio_gpu_resource_sn"
    "apshot.proto\032#virtio_gpu_timelines_snaps"
    "hot.proto\"\352\003\n\031VirtioGpuFrontendSnapshot\022"
    "R\n\010contexts\030\001 \003(\0132@.gfxstream.host.snaps"
    "hot.VirtioGpuFrontendSnapshot.ContextsEn"
    "try\022T\n\tresources\030\002 \003(\0132A.gfxstream.host."
    "snapshot.VirtioGpuFrontendSnapshot.Resou"
    "rcesEntry\022K\n\ttimelines\030\003 \001(\01323.gfxstream"
    ".host.snapshot.VirtioGpuTimelinesSnapsho"
    "tH\000\210\001\001\032b\n\rContextsEntry\022\013\n\003key\030\001 \001(\r\022@\n\005"
    "value\030\002 \001(\01321.gfxstream.host.snapshot.Vi"
    "rtioGpuContextSnapshot:\0028\001\032d\n\016ResourcesE"
    "ntry\022\013\n\003key\030\001 \001(\r\022A\n\005value\030\002 \001(\01322.gfxst"
    "ream.host.snapshot.VirtioGpuResourceSnap"
    "shot:\0028\001B\014\n\n_timelinesb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto_deps[3] = {
        &::descriptor_table_virtio_5fgpu_5fcontext_5fsnapshot_2eproto,
        &::descriptor_table_virtio_5fgpu_5fresource_5fsnapshot_2eproto,
        &::descriptor_table_virtio_5fgpu_5ftimelines_5fsnapshot_2eproto,
};
static ::absl::once_flag descriptor_table_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto = {
    false,
    false,
    670,
    descriptor_table_protodef_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto,
    "virtio_gpu_frontend_snapshot.proto",
    &descriptor_table_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto_once,
    descriptor_table_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto_deps,
    3,
    3,
    schemas,
    file_message_globals,
    TableStruct_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto::offsets,
    file_level_enum_descriptors_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto,
    file_level_service_descriptors_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto,
};
namespace gfxstream {
namespace host {
namespace snapshot {
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse::VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse() : Super_(VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse_get_class_data()) {}
VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse::VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : Super_(arena, VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse_get_class_data()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse::VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse() : Super_() {}
VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse::VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : Super_(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse_class_data_ =
        VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse::InternalGenerateClassData_(VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse_globals_._default);

// including ~ all the vtables and everything they use become part
// of the same ~ SCC.
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse_class_data_.tc_table);
  return VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse_globals_));
  return VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse::ParseTableT_
    VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse::_table_ =
        VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse::InternalGenerateParseTable_(VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse::VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse() : Super_(VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse_get_class_data()) {}
VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse::VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : Super_(arena, VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse_get_class_data()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse::VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse() : Super_() {}
VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse::VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : Super_(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse_class_data_ =
        VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse::InternalGenerateClassData_(VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse_globals_._default);

// including ~ all the vtables and everything they use become part
// of the same ~ SCC.
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse_class_data_.tc_table);
  return VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse_globals_));
  return VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse::ParseTableT_
    VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse::_table_ =
        VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse::InternalGenerateParseTable_(VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
// ===================================================================

void VirtioGpuFrontendSnapshot::clear_contexts() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.contexts_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
void VirtioGpuFrontendSnapshot::clear_resources() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.resources_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
void VirtioGpuFrontendSnapshot::clear_timelines() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.timelines_ != nullptr) _impl_.timelines_->Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
VirtioGpuFrontendSnapshot::VirtioGpuFrontendSnapshot(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, VirtioGpuFrontendSnapshot_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gfxstream.host.snapshot.VirtioGpuFrontendSnapshot)
}
PROTOBUF_NDEBUG_INLINE VirtioGpuFrontendSnapshot::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot& from_msg)
      : _has_bits_{from._has_bits_},
        contexts_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot,
              PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot, _impl_.contexts_)>()
          , arena, from.contexts_
        }
        ,
        resources_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot,
              PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot, _impl_.resources_)>()
          , arena, from.resources_
        }
     {}

VirtioGpuFrontendSnapshot::VirtioGpuFrontendSnapshot(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const VirtioGpuFrontendSnapshot& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, VirtioGpuFrontendSnapshot_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  VirtioGpuFrontendSnapshot* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.timelines_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                 ? Super_::CopyConstruct(arena, *from._impl_.timelines_)
                 : nullptr;

  // @@protoc_insertion_point(copy_constructor:gfxstream.host.snapshot.VirtioGpuFrontendSnapshot)
}
PROTOBUF_NDEBUG_INLINE VirtioGpuFrontendSnapshot::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : contexts_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot,
            PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot, _impl_.contexts_)>()
         }
        ,
        resources_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot,
            PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuFrontendSnapshot, _impl_.resources_)>()
         }
     {}

inline void VirtioGpuFrontendSnapshot::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.timelines_ = {};
}
VirtioGpuFrontendSnapshot::~VirtioGpuFrontendSnapshot() {
  // @@protoc_insertion_point(destructor:gfxstream.host.snapshot.VirtioGpuFrontendSnapshot)
  SharedDtor(*this);
}
inline void VirtioGpuFrontendSnapshot::SharedDtor(MessageLite& self) {
  VirtioGpuFrontendSnapshot& this_ = static_cast<VirtioGpuFrontendSnapshot&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.timelines_;
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull VirtioGpuFrontendSnapshot_class_data_ =
        VirtioGpuFrontendSnapshot::InternalGenerateClassData_(VirtioGpuFrontendSnapshot_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VirtioGpuFrontendSnapshot::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&VirtioGpuFrontendSnapshot_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(VirtioGpuFrontendSnapshot_class_data_.tc_table);
  return VirtioGpuFrontendSnapshot_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VirtioGpuFrontendSnapshot::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&VirtioGpuFrontendSnapshot_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&VirtioGpuFrontendSnapshot_globals_));
  return VirtioGpuFrontendSnapshot_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const VirtioGpuFrontendSnapshot::ParseTableT_
    VirtioGpuFrontendSnapshot::_table_ =
        VirtioGpuFrontendSnapshot::InternalGenerateParseTable_(VirtioGpuFrontendSnapshot_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void VirtioGpuFrontendSnapshot::Clear() {
  auto& this_ [[maybe_unused]] = *this;
  // @@protoc_insertion_point(message_clear_start:gfxstream.host.snapshot.VirtioGpuFrontendSnapshot)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(this_._impl_.timelines_ != nullptr);
      this_._impl_.timelines_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.contexts_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.resources_.Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL VirtioGpuFrontendSnapshot::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const VirtioGpuFrontendSnapshot& this_ = static_cast<const VirtioGpuFrontendSnapshot&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL VirtioGpuFrontendSnapshot::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const VirtioGpuFrontendSnapshot& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:gfxstream.host.snapshot.VirtioGpuFrontendSnapshot)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // map<uint32, .gfxstream.host.snapshot.VirtioGpuContextSnapshot> contexts = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_contexts().empty()) {
      using MapType = ::google::protobuf::Map<::uint32_t, ::gfxstream::host::snapshot::VirtioGpuContextSnapshot>;
      using WireHelper = _pbi::MapEntryFuncs<::uint32_t, ::gfxstream::host::snapshot::VirtioGpuContextSnapshot,
                                     _pbi::WireFormatLite::TYPE_UINT32,
                                     _pbi::WireFormatLite::TYPE_MESSAGE>;
      const auto& field = this_._internal_contexts();

      if (stream->IsSerializationDeterministic() && field.size() > 1) {
        for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
          target = WireHelper::InternalSerialize(
              1, entry.first, entry.second, target, stream);
        }
      } else {
        for (const auto& entry : field) {
          target = WireHelper::InternalSerialize(
              1, entry.first, entry.second, target, stream);
        }
      }
    }
  }

  // map<uint32, .gfxstream.host.snapshot.VirtioGpuResourceSnapshot> resources = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_resources().empty()) {
      using MapType = ::google::protobuf::Map<::uint32_t, ::gfxstream::host::snapshot::VirtioGpuResourceSnapshot>;
      using WireHelper = _pbi::MapEntryFuncs<::uint32_t, ::gfxstream::host::snapshot::VirtioGpuResourceSnapshot,
                                     _pbi::WireFormatLite::TYPE_UINT32,
                                     _pbi::WireFormatLite::TYPE_MESSAGE>;
      const auto& field = this_._internal_resources();

      if (stream->IsSerializationDeterministic() && field.size() > 1) {
        for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
          target = WireHelper::InternalSerialize(
              2, entry.first, entry.second, target, stream);
        }
      } else {
        for (const auto& entry : field) {
          target = WireHelper::InternalSerialize(
              2, entry.first, entry.second, target, stream);
        }
      }
    }
  }

  // optional .gfxstream.host.snapshot.VirtioGpuTimelinesSnapshot timelines = 3;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.timelines_, this_._impl_.timelines_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gfxstream.host.snapshot.VirtioGpuFrontendSnapshot)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t VirtioGpuFrontendSnapshot::ByteSizeLong(const MessageLite& base) {
  const VirtioGpuFrontendSnapshot& this_ = static_cast<const VirtioGpuFrontendSnapshot&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t VirtioGpuFrontendSnapshot::ByteSizeLong() const {
  const VirtioGpuFrontendSnapshot& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:gfxstream.host.snapshot.VirtioGpuFrontendSnapshot)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // optional .gfxstream.host.snapshot.VirtioGpuTimelinesSnapshot timelines = 3;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.timelines_);
    }
    // map<uint32, .gfxstream.host.snapshot.VirtioGpuContextSnapshot> contexts = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_contexts_size());
      for (const auto& entry : this_._internal_contexts()) {
        total_size += _pbi::MapEntryFuncs<::uint32_t, ::gfxstream::host::snapshot::VirtioGpuContextSnapshot,
                                       _pbi::WireFormatLite::TYPE_UINT32,
                                       _pbi::WireFormatLite::TYPE_MESSAGE>::ByteSizeLong(entry.first, entry.second);
      }
    }
    // map<uint32, .gfxstream.host.snapshot.VirtioGpuResourceSnapshot> resources = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_resources_size());
      for (const auto& entry : this_._internal_resources()) {
        total_size += _pbi::MapEntryFuncs<::uint32_t, ::gfxstream::host::snapshot::VirtioGpuResourceSnapshot,
                                       _pbi::WireFormatLite::TYPE_UINT32,
                                       _pbi::WireFormatLite::TYPE_MESSAGE>::ByteSizeLong(entry.first, entry.second);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void VirtioGpuFrontendSnapshot::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<VirtioGpuFrontendSnapshot*>(&to_msg);
  auto& from = static_cast<const VirtioGpuFrontendSnapshot&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:gfxstream.host.snapshot.VirtioGpuFrontendSnapshot)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.timelines_ != nullptr);
      if (_this->_impl_.timelines_ == nullptr) {
        _this->_impl_.timelines_ = Super_::CopyConstruct(arena, *from._impl_.timelines_);
      } else {
        _this->_impl_.timelines_->MergeFrom(*from._impl_.timelines_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.contexts_.MergeFrom(from._impl_.contexts_);
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.resources_.MergeFrom(from._impl_.resources_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void VirtioGpuFrontendSnapshot::CopyFrom(const VirtioGpuFrontendSnapshot& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:gfxstream.host.snapshot.VirtioGpuFrontendSnapshot)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void VirtioGpuFrontendSnapshot::InternalSwap(VirtioGpuFrontendSnapshot* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.timelines_, other->_impl_.timelines_);
  _impl_.contexts_.InternalSwap(&other->_impl_.contexts_);
  _impl_.resources_.InternalSwap(&other->_impl_.resources_);
}

::google::protobuf::Metadata VirtioGpuFrontendSnapshot::GetMetadata() const {
  return Super_::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace snapshot
}  // namespace host
}  // namespace gfxstream
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
