// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: virtio_gpu_context_snapshot.proto
// Protobuf C++ Version: 7.36.1

#include "virtio_gpu_context_snapshot.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::gfxstream::host::snapshot::VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse
        {&::_pbi::kDescriptorMethods, &::descriptor_table_virtio_5fgpu_5fcontext_5fsnapshot_2eproto, /* tracker*/ nullptr,},
        // ::gfxstream::host::snapshot::VirtioGpuContextSnapshot
        {&::_pbi::kDescriptorMethods, &::descriptor_table_virtio_5fgpu_5fcontext_5fsnapshot_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
namespace gfxstream {
namespace host {
namespace snapshot {
constexpr VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse::ParseTableT_ VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse, _impl_._has_bits_),
      0, // no _extensions_
      2, 8,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967292,  // skipmap
      offsetof(ParseTableT_, field_entries),
      2,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::gfxstream::host::snapshot::VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // uint32 value = 2;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse, _impl_.value_), 1>(),
       {16, 1, 0,
        PROTOBUF_FIELD_OFFSET(VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse, _impl_.value_)}},
      // uint32 key = 1;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse, _impl_.key_), 0>(),
       {8, 0, 0,
        PROTOBUF_FIELD_OFFSET(VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse, _impl_.key_)}},
    }}, {{
      65535, 65535
    }}, {{
      // uint32 key = 1;
      {PROTOBUF_FIELD_OFFSET(VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // uint32 value = 2;
      {PROTOBUF_FIELD_OFFSET(VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    }},
    // no aux_entries
    {{
    }},
  };
}

template <typename>
constexpr VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse::VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
      ) {
}
inline void* PROTOBUF_NONNULL VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse(arena);
}
constexpr auto VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse), alignof(VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse));
}
constexpr auto VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse::MergeImpl,
          Super_::GetNewImpl<VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse::ClearImpl),
              Super_::ByteSizeLongImpl, Super_::_InternalSerializeImpl,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_virtio_5fgpu_5fcontext_5fsnapshot_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUseGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUseGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse::InternalGenerateClassData_(
            _default, &VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUseGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUseGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUseGlobalsTypeInternal VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse_globals_.GetClassData();
#else
  return VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class VirtioGpuContextSnapshot::_Internal {
 public:
  using HasBits = decltype(::std::declval<VirtioGpuContextSnapshot>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(VirtioGpuContextSnapshot, _impl_._has_bits_);
};

constexpr VirtioGpuContextSnapshot::ParseTableT_ VirtioGpuContextSnapshot::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(VirtioGpuContextSnapshot, _impl_._has_bits_),
      0, // no _extensions_
      5, 24,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967264,  // skipmap
      offsetof(ParseTableT_, field_entries),
      5,  // num_field_entries
      1,  // num_aux_entries
      offsetof(ParseTableT_, aux_entries),
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::MpUnknownFields,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::gfxstream::host::snapshot::VirtioGpuContextSnapshot>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // repeated uint32 attached_resources = 4;
      {::_pbi::TcParser::FastV32P1,
       {34, 0, 0,
        PROTOBUF_FIELD_OFFSET(VirtioGpuContextSnapshot, _impl_.attached_resources_)}},
      // optional uint32 id = 1;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VirtioGpuContextSnapshot, _impl_.id_), 2>(),
       {8, 2, 0,
        PROTOBUF_FIELD_OFFSET(VirtioGpuContextSnapshot, _impl_.id_)}},
      // optional string name = 2;
      {::_pbi::TcParser::FastUS1,
       {18, 1, 0,
        PROTOBUF_FIELD_OFFSET(VirtioGpuContextSnapshot, _impl_.name_)}},
      // optional uint32 capset = 3;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VirtioGpuContextSnapshot, _impl_.capset_), 3>(),
       {24, 3, 0,
        PROTOBUF_FIELD_OFFSET(VirtioGpuContextSnapshot, _impl_.capset_)}},
    }}, {{
      65535, 65535
    }}, {{
      // optional uint32 id = 1;
      {PROTOBUF_FIELD_OFFSET(VirtioGpuContextSnapshot, _impl_.id_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // optional string name = 2;
      {PROTOBUF_FIELD_OFFSET(VirtioGpuContextSnapshot, _impl_.name_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // optional uint32 capset = 3;
      {PROTOBUF_FIELD_OFFSET(VirtioGpuContextSnapshot, _impl_.capset_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // repeated uint32 attached_resources = 4;
      {PROTOBUF_FIELD_OFFSET(VirtioGpuContextSnapshot, _impl_.attached_resources_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
      // map<uint32, uint32> resource_asgs = 5;
      {PROTOBUF_FIELD_OFFSET(VirtioGpuContextSnapshot, _impl_.resource_asgs_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
    }},
    {{
        {::_pbi::TcParser::GetMapAuxInfo(
            0, 0, 13, 13, 0)},
    }},
    {{
      "\60\0\4\0\0\0\0\0"
      "gfxstream.host.snapshot.VirtioGpuContextSnapshot"
      "name"
    }},
  };
}


inline constexpr VirtioGpuContextSnapshot::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : attached_resources_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::gfxstream::host::snapshot::VirtioGpuContextSnapshot,
            PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuContextSnapshot, _impl_.attached_resources_)>()
         }
        ,
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0u},
        capset_{0u},
        resource_asgs_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::gfxstream::host::snapshot::VirtioGpuContextSnapshot,
            PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuContextSnapshot, _impl_.resource_asgs_)>()
         }
     {}

template <typename>
constexpr VirtioGpuContextSnapshot::VirtioGpuContextSnapshot(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL VirtioGpuContextSnapshot::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) VirtioGpuContextSnapshot(arena);
}
constexpr auto VirtioGpuContextSnapshot::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(VirtioGpuContextSnapshot), alignof(VirtioGpuContextSnapshot));
}
constexpr auto VirtioGpuContextSnapshot::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &VirtioGpuContextSnapshot::MergeImpl,
          Super_::GetNewImpl<VirtioGpuContextSnapshot>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &VirtioGpuContextSnapshot::SharedDtor,
          Super_::GetClearImpl<VirtioGpuContextSnapshot>(), &VirtioGpuContextSnapshot::ByteSizeLong,
              &VirtioGpuContextSnapshot::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(VirtioGpuContextSnapshot, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[1],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_virtio_5fgpu_5fcontext_5fsnapshot_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct VirtioGpuContextSnapshotGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr VirtioGpuContextSnapshotGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 VirtioGpuContextSnapshot_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(VirtioGpuContextSnapshot::InternalGenerateClassData_(
            _default, &VirtioGpuContextSnapshot_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<VirtioGpuContextSnapshot>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~VirtioGpuContextSnapshotGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) VirtioGpuContextSnapshot _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<VirtioGpuContextSnapshot>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(VirtioGpuContextSnapshotGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST VirtioGpuContextSnapshotGlobalsTypeInternal VirtioGpuContextSnapshot_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* VirtioGpuContextSnapshot_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return VirtioGpuContextSnapshot_globals_.GetClassData();
#else
  return VirtioGpuContextSnapshot_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace snapshot
}  // namespace host
}  // namespace gfxstream
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_virtio_5fgpu_5fcontext_5fsnapshot_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_virtio_5fgpu_5fcontext_5fsnapshot_2eproto = nullptr;
const ::uint32_t
    TableStruct_virtio_5fgpu_5fcontext_5fsnapshot_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse, _impl_.value_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuContextSnapshot, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuContextSnapshot, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuContextSnapshot, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuContextSnapshot, _impl_.capset_),
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuContextSnapshot, _impl_.attached_resources_),
        PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuContextSnapshot, _impl_.resource_asgs_),
        2,
        1,
        3,
        0,
        4,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::gfxstream::host::snapshot::VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse)},
        {7, sizeof(::gfxstream::host::snapshot::VirtioGpuContextSnapshot)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::gfxstream::host::snapshot::VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse_globals_,
        &::gfxstream::host::snapshot::VirtioGpuContextSnapshot_globals_,
};
const char descriptor_table_protodef_virtio_5fgpu_5fcontext_5fsnapshot_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n!virtio_gpu_context_snapshot.proto\022\027gfx"
    "stream.host.snapshot\"\233\002\n\030VirtioGpuContex"
    "tSnapshot\022\017\n\002id\030\001 \001(\rH\000\210\001\001\022\021\n\004name\030\002 \001(\t"
    "H\001\210\001\001\022\023\n\006capset\030\003 \001(\rH\002\210\001\001\022\032\n\022attached_r"
    "esources\030\004 \003(\r\022Z\n\rresource_asgs\030\005 \003(\0132C."
    "gfxstream.host.snapshot.VirtioGpuContext"
    "Snapshot.ResourceAsgsEntry\0323\n\021ResourceAs"
    "gsEntry\022\013\n\003key\030\001 \001(\r\022\r\n\005value\030\002 \001(\r:\0028\001B"
    "\005\n\003_idB\007\n\005_nameB\t\n\007_capsetb\006proto3"
};
static ::absl::once_flag descriptor_table_virtio_5fgpu_5fcontext_5fsnapshot_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_virtio_5fgpu_5fcontext_5fsnapshot_2eproto = {
    false,
    false,
    354,
    descriptor_table_protodef_virtio_5fgpu_5fcontext_5fsnapshot_2eproto,
    "virtio_gpu_context_snapshot.proto",
    &descriptor_table_virtio_5fgpu_5fcontext_5fsnapshot_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_message_globals,
    TableStruct_virtio_5fgpu_5fcontext_5fsnapshot_2eproto::offsets,
    file_level_enum_descriptors_virtio_5fgpu_5fcontext_5fsnapshot_2eproto,
    file_level_service_descriptors_virtio_5fgpu_5fcontext_5fsnapshot_2eproto,
};
namespace gfxstream {
namespace host {
namespace snapshot {
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse::VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse() : Super_(VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse_get_class_data()) {}
VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse::VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : Super_(arena, VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse_get_class_data()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse::VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse() : Super_() {}
VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse::VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : Super_(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse_class_data_ =
        VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse::InternalGenerateClassData_(VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse_globals_._default);

// including ~ all the vtables and everything they use become part
// of the same ~ SCC.
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse_class_data_.tc_table);
  return VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse_globals_));
  return VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse::ParseTableT_
    VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse::_table_ =
        VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse::InternalGenerateParseTable_(VirtioGpuContextSnapshot_ResourceAsgsEntry_DoNotUse_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
// ===================================================================

VirtioGpuContextSnapshot::VirtioGpuContextSnapshot(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, VirtioGpuContextSnapshot_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gfxstream.host.snapshot.VirtioGpuContextSnapshot)
}
PROTOBUF_NDEBUG_INLINE VirtioGpuContextSnapshot::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::gfxstream::host::snapshot::VirtioGpuContextSnapshot& from_msg)
      : _has_bits_{from._has_bits_},
        attached_resources_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::gfxstream::host::snapshot::VirtioGpuContextSnapshot,
              PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuContextSnapshot, _impl_.attached_resources_)>()
          , arena, from.attached_resources_
        }
        ,
        name_(arena, from.name_),
        resource_asgs_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::gfxstream::host::snapshot::VirtioGpuContextSnapshot,
              PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuContextSnapshot, _impl_.resource_asgs_)>()
          , arena, from.resource_asgs_
        }
     {}

VirtioGpuContextSnapshot::VirtioGpuContextSnapshot(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const VirtioGpuContextSnapshot& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, VirtioGpuContextSnapshot_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  VirtioGpuContextSnapshot* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, capset_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::capset_));

  // @@protoc_insertion_point(copy_constructor:gfxstream.host.snapshot.VirtioGpuContextSnapshot)
}
PROTOBUF_NDEBUG_INLINE VirtioGpuContextSnapshot::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : attached_resources_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::gfxstream::host::snapshot::VirtioGpuContextSnapshot,
            PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuContextSnapshot, _impl_.attached_resources_)>()
         }
        ,
        name_(arena),
        resource_asgs_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::gfxstream::host::snapshot::VirtioGpuContextSnapshot,
            PROTOBUF_FIELD_OFFSET(::gfxstream::host::snapshot::VirtioGpuContextSnapshot, _impl_.resource_asgs_)>()
         }
     {}

inline void VirtioGpuContextSnapshot::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, capset_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::capset_));
}
VirtioGpuContextSnapshot::~VirtioGpuContextSnapshot() {
  // @@protoc_insertion_point(destructor:gfxstream.host.snapshot.VirtioGpuContextSnapshot)
  SharedDtor(*this);
}
inline void VirtioGpuContextSnapshot::SharedDtor(MessageLite& self) {
  VirtioGpuContextSnapshot& this_ = static_cast<VirtioGpuContextSnapshot&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull VirtioGpuContextSnapshot_class_data_ =
        VirtioGpuContextSnapshot::InternalGenerateClassData_(VirtioGpuContextSnapshot_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VirtioGpuContextSnapshot::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&VirtioGpuContextSnapshot_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(VirtioGpuContextSnapshot_class_data_.tc_table);
  return VirtioGpuContextSnapshot_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VirtioGpuContextSnapshot::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&VirtioGpuContextSnapshot_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&VirtioGpuContextSnapshot_globals_));
  return VirtioGpuContextSnapshot_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const VirtioGpuContextSnapshot::ParseTableT_
    VirtioGpuContextSnapshot::_table_ =
        VirtioGpuContextSnapshot::InternalGenerateParseTable_(VirtioGpuContextSnapshot_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void VirtioGpuContextSnapshot::Clear() {
  auto& this_ [[maybe_unused]] = *this;
  // @@protoc_insertion_point(message_clear_start:gfxstream.host.snapshot.VirtioGpuContextSnapshot)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.attached_resources_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      this_._impl_.name_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000001cU)) {
    ::memset(&this_._impl_.id_, 0,
             static_cast<::size_t>(
                 reinterpret_cast<char*>(&this_._impl_.capset_) -
                 reinterpret_cast<char*>(&this_._impl_.id_)) +
                 sizeof(_impl_.capset_));
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _impl_.resource_asgs_.Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL VirtioGpuContextSnapshot::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const VirtioGpuContextSnapshot& this_ = static_cast<const VirtioGpuContextSnapshot&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL VirtioGpuContextSnapshot::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const VirtioGpuContextSnapshot& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:gfxstream.host.snapshot.VirtioGpuContextSnapshot)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_id(), target);
  }

  // optional string name = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::std::string& _s = this_._internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "gfxstream.host.snapshot.VirtioGpuContextSnapshot.name");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // optional uint32 capset = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this_._internal_capset(), target);
  }

  // repeated uint32 attached_resources = 4;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    {
      int byte_size = this_._impl_._attached_resources_cached_byte_size_.Get();
      if (byte_size > 0) {
        target = stream->WriteUInt32Packed(
            4, this_._internal_attached_resources(), byte_size, target);
      }
    }
  }

  // map<uint32, uint32> resource_asgs = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (!this_._internal_resource_asgs().empty()) {
      using MapType = ::google::protobuf::Map<::uint32_t, ::uint32_t>;
      using WireHelper = _pbi::MapEntryFuncs<::uint32_t, ::uint32_t,
                                     _pbi::WireFormatLite::TYPE_UINT32,
                                     _pbi::WireFormatLite::TYPE_UINT32>;
      const auto& field = this_._internal_resource_asgs();

      if (stream->IsSerializationDeterministic() && field.size() > 1) {
        for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
          target = WireHelper::InternalSerialize(
              5, entry.first, entry.second, target, stream);
        }
      } else {
        for (const auto& entry : field) {
          target = WireHelper::InternalSerialize(
              5, entry.first, entry.second, target, stream);
        }
      }
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gfxstream.host.snapshot.VirtioGpuContextSnapshot)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t VirtioGpuContextSnapshot::ByteSizeLong(const MessageLite& base) {
  const VirtioGpuContextSnapshot& this_ = static_cast<const VirtioGpuContextSnapshot&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t VirtioGpuContextSnapshot::ByteSizeLong() const {
  const VirtioGpuContextSnapshot& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:gfxstream.host.snapshot.VirtioGpuContextSnapshot)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // repeated uint32 attached_resources = 4;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size +=
          ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
              this_._internal_attached_resources(), 1,
              this_._impl_._attached_resources_cached_byte_size_);
    }
    // optional string name = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_name());
    }
    // optional uint32 id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_id());
    }
    // optional uint32 capset = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_capset());
    }
    // map<uint32, uint32> resource_asgs = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_resource_asgs_size());
      for (const auto& entry : this_._internal_resource_asgs()) {
        total_size += _pbi::MapEntryFuncs<::uint32_t, ::uint32_t,
                                       _pbi::WireFormatLite::TYPE_UINT32,
                                       _pbi::WireFormatLite::TYPE_UINT32>::ByteSizeLong(entry.first, entry.second);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void VirtioGpuContextSnapshot::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<VirtioGpuContextSnapshot*>(&to_msg);
  auto& from = static_cast<const VirtioGpuContextSnapshot&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:gfxstream.host.snapshot.VirtioGpuContextSnapshot)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_attached_resources()->MergeFrom(from._internal_attached_resources());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_name(from._internal_name());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.id_ = from._impl_.id_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.capset_ = from._impl_.capset_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.resource_asgs_.MergeFrom(from._impl_.resource_asgs_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void VirtioGpuContextSnapshot::CopyFrom(const VirtioGpuContextSnapshot& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:gfxstream.host.snapshot.VirtioGpuContextSnapshot)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void VirtioGpuContextSnapshot::InternalSwap(VirtioGpuContextSnapshot* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.attached_resources_.InternalSwap(&other->_impl_.attached_resources_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VirtioGpuContextSnapshot, _impl_.capset_)
      + sizeof(VirtioGpuContextSnapshot::_impl_.capset_)
      - PROTOBUF_FIELD_OFFSET(VirtioGpuContextSnapshot, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
  _impl_.resource_asgs_.InternalSwap(&other->_impl_.resource_asgs_);
}

::google::protobuf::Metadata VirtioGpuContextSnapshot::GetMetadata() const {
  return Super_::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace snapshot
}  // namespace host
}  // namespace gfxstream
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_virtio_5fgpu_5fcontext_5fsnapshot_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
