// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: virtio_gpu_frontend_snapshot.proto
// Protobuf C++ Version: 7.36.1

#ifndef virtio_5fgpu_5ffrontend_5fsnapshot_2eproto_2epb_2eh
#define virtio_5fgpu_5ffrontend_5fsnapshot_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7036001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_type_handler.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field.h"
#include "google/protobuf/unknown_field_set.h"
#include "virtio_gpu_context_snapshot.pb.h"
#include "virtio_gpu_resource_snapshot.pb.h"
#include "virtio_gpu_timelines_snapshot.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto;
}  // extern "C"
namespace gfxstream {
namespace host {
namespace snapshot {
class VirtioGpuFrontendSnapshot;
struct VirtioGpuFrontendSnapshotGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern VirtioGpuFrontendSnapshotGlobalsTypeInternal VirtioGpuFrontendSnapshot_globals_;
extern const ::google::protobuf::internal::ClassDataFull VirtioGpuFrontendSnapshot_class_data_;
#else
extern const VirtioGpuFrontendSnapshotGlobalsTypeInternal VirtioGpuFrontendSnapshot_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse;
struct VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUseGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUseGlobalsTypeInternal VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse_globals_;
extern const ::google::protobuf::internal::ClassDataFull VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse_class_data_;
#else
extern const VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUseGlobalsTypeInternal VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse;
struct VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUseGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUseGlobalsTypeInternal VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse_globals_;
extern const ::google::protobuf::internal::ClassDataFull VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse_class_data_;
#else
extern const VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUseGlobalsTypeInternal VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace snapshot
}  // namespace host
}  // namespace gfxstream
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace gfxstream {
namespace host {
namespace snapshot {

// ===================================================================


// -------------------------------------------------------------------

class PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::uint32_t, ::google::protobuf::Message,
                             ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
                             ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
  using Super_ =
      ::google::protobuf::internal::MapEntry<::uint32_t, ::google::protobuf::Message,
                      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;

 public:
  VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse();
  template <typename = void>
  explicit constexpr VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);
  explicit VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_message_globals() {
    return &VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse_globals_;
  }


  static constexpr auto InternalGenerateClassData_(
      const ::google::protobuf::MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto;
  friend ::google::protobuf::internal::PrivateAccess;
  friend VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUseGlobalsTypeInternal;

  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<1, 2,
                          1, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
// -------------------------------------------------------------------

class PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::uint32_t, ::google::protobuf::Message,
                             ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
                             ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
  using Super_ =
      ::google::protobuf::internal::MapEntry<::uint32_t, ::google::protobuf::Message,
                      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;

 public:
  VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse();
  template <typename = void>
  explicit constexpr VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);
  explicit VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_message_globals() {
    return &VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse_globals_;
  }


  static constexpr auto InternalGenerateClassData_(
      const ::google::protobuf::MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto;
  friend ::google::protobuf::internal::PrivateAccess;
  friend VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUseGlobalsTypeInternal;

  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<1, 2,
                          1, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED VirtioGpuFrontendSnapshot final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:gfxstream.host.snapshot.VirtioGpuFrontendSnapshot) */ {
  using Super_ = ::google::protobuf::Message;

 public:
  inline VirtioGpuFrontendSnapshot() : VirtioGpuFrontendSnapshot(nullptr) {}
  ~VirtioGpuFrontendSnapshot() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(VirtioGpuFrontendSnapshot* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(VirtioGpuFrontendSnapshot));
  }
#endif

  template <typename = void>
  explicit constexpr VirtioGpuFrontendSnapshot(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline VirtioGpuFrontendSnapshot(const VirtioGpuFrontendSnapshot& from) : VirtioGpuFrontendSnapshot(nullptr, from) {}
  inline VirtioGpuFrontendSnapshot(VirtioGpuFrontendSnapshot&& from) noexcept : VirtioGpuFrontendSnapshot(nullptr, ::std::move(from)) {}
  inline VirtioGpuFrontendSnapshot& operator=(const VirtioGpuFrontendSnapshot& from) {
    CopyFrom(from);
    return *this;
  }
  inline VirtioGpuFrontendSnapshot& operator=(VirtioGpuFrontendSnapshot&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const VirtioGpuFrontendSnapshot& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<VirtioGpuFrontendSnapshot>(&VirtioGpuFrontendSnapshot_globals_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(VirtioGpuFrontendSnapshot& a, VirtioGpuFrontendSnapshot& b) { a.Swap(&b); }
  inline void Swap(VirtioGpuFrontendSnapshot* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VirtioGpuFrontendSnapshot* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] VirtioGpuFrontendSnapshot* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return Super_::DefaultConstruct<VirtioGpuFrontendSnapshot>(arena);
  }
  using Super_::CopyFrom;
  void CopyFrom(const VirtioGpuFrontendSnapshot& from);
  using Super_::MergeFrom;
  void MergeFrom(const VirtioGpuFrontendSnapshot& from) { VirtioGpuFrontendSnapshot::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(VirtioGpuFrontendSnapshot* PROTOBUF_NONNULL other);
 private:
  static ::absl::string_view FullMessageName() { return "gfxstream.host.snapshot.VirtioGpuFrontendSnapshot"; }

  explicit VirtioGpuFrontendSnapshot(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  VirtioGpuFrontendSnapshot(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const VirtioGpuFrontendSnapshot& from);
  VirtioGpuFrontendSnapshot(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, VirtioGpuFrontendSnapshot&& from) noexcept
      : VirtioGpuFrontendSnapshot(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTimelinesFieldNumber = 3,
    kContextsFieldNumber = 1,
    kResourcesFieldNumber = 2,
  };
  // optional .gfxstream.host.snapshot.VirtioGpuTimelinesSnapshot timelines = 3;
  [[nodiscard]] bool has_timelines() const;
  void clear_timelines() ;
  [[nodiscard]] const ::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot& timelines() const;
  [[nodiscard]] ::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot* PROTOBUF_NULLABLE release_timelines();
  ::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot* PROTOBUF_NONNULL mutable_timelines();
  void set_allocated_timelines(::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_timelines(::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot* PROTOBUF_NULLABLE value);
  ::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot* PROTOBUF_NULLABLE unsafe_arena_release_timelines();

  private:
  const ::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot& _internal_timelines() const;
  ::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot* PROTOBUF_NONNULL _internal_mutable_timelines();

  public:
  // map<uint32, .gfxstream.host.snapshot.VirtioGpuContextSnapshot> contexts = 1;
  [[nodiscard]] int contexts_size() const;
  private:
  int _internal_contexts_size() const;

  public:
  void clear_contexts() ;
  [[nodiscard]] const ::google::protobuf::Map<::uint32_t, ::gfxstream::host::snapshot::VirtioGpuContextSnapshot>& contexts() const;
  [[nodiscard]] ::google::protobuf::Map<::uint32_t, ::gfxstream::host::snapshot::VirtioGpuContextSnapshot>* PROTOBUF_NONNULL mutable_contexts();

  private:
  const ::google::protobuf::Map<::uint32_t, ::gfxstream::host::snapshot::VirtioGpuContextSnapshot>& _internal_contexts() const;
  ::google::protobuf::Map<::uint32_t, ::gfxstream::host::snapshot::VirtioGpuContextSnapshot>* PROTOBUF_NONNULL _internal_mutable_contexts();

  public:
  // map<uint32, .gfxstream.host.snapshot.VirtioGpuResourceSnapshot> resources = 2;
  [[nodiscard]] int resources_size() const;
  private:
  int _internal_resources_size() const;

  public:
  void clear_resources() ;
  [[nodiscard]] const ::google::protobuf::Map<::uint32_t, ::gfxstream::host::snapshot::VirtioGpuResourceSnapshot>& resources() const;
  [[nodiscard]] ::google::protobuf::Map<::uint32_t, ::gfxstream::host::snapshot::VirtioGpuResourceSnapshot>* PROTOBUF_NONNULL mutable_resources();

  private:
  const ::google::protobuf::Map<::uint32_t, ::gfxstream::host::snapshot::VirtioGpuResourceSnapshot>& _internal_resources() const;
  ::google::protobuf::Map<::uint32_t, ::gfxstream::host::snapshot::VirtioGpuResourceSnapshot>* PROTOBUF_NONNULL _internal_mutable_resources();

  public:
  // @@protoc_insertion_point(class_scope:gfxstream.host.snapshot.VirtioGpuFrontendSnapshot)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<0, 3,
                          5, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const VirtioGpuFrontendSnapshot& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot* PROTOBUF_NULLABLE timelines_;
    ::google::protobuf::internal::MapField<VirtioGpuFrontendSnapshot_ContextsEntry_DoNotUse, ::uint32_t, ::gfxstream::host::snapshot::VirtioGpuContextSnapshot> contexts_;
    ::google::protobuf::internal::MapField<VirtioGpuFrontendSnapshot_ResourcesEntry_DoNotUse, ::uint32_t, ::gfxstream::host::snapshot::VirtioGpuResourceSnapshot> resources_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_virtio_5fgpu_5ffrontend_5fsnapshot_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// VirtioGpuFrontendSnapshot

// map<uint32, .gfxstream.host.snapshot.VirtioGpuContextSnapshot> contexts = 1;
inline int VirtioGpuFrontendSnapshot::_internal_contexts_size() const {
  return _internal_contexts().size();
}
inline int VirtioGpuFrontendSnapshot::contexts_size() const {
  return _internal_contexts_size();
}
inline const ::google::protobuf::Map<::uint32_t, ::gfxstream::host::snapshot::VirtioGpuContextSnapshot>& VirtioGpuFrontendSnapshot::_internal_contexts() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.contexts_.GetMap();
}
inline const ::google::protobuf::Map<::uint32_t, ::gfxstream::host::snapshot::VirtioGpuContextSnapshot>& VirtioGpuFrontendSnapshot::contexts() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:gfxstream.host.snapshot.VirtioGpuFrontendSnapshot.contexts)
  return _internal_contexts();
}
inline ::google::protobuf::Map<::uint32_t, ::gfxstream::host::snapshot::VirtioGpuContextSnapshot>* PROTOBUF_NONNULL VirtioGpuFrontendSnapshot::_internal_mutable_contexts() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.contexts_.MutableMap();
}
inline ::google::protobuf::Map<::uint32_t, ::gfxstream::host::snapshot::VirtioGpuContextSnapshot>* PROTOBUF_NONNULL VirtioGpuFrontendSnapshot::mutable_contexts()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_map:gfxstream.host.snapshot.VirtioGpuFrontendSnapshot.contexts)
  return _internal_mutable_contexts();
}

// map<uint32, .gfxstream.host.snapshot.VirtioGpuResourceSnapshot> resources = 2;
inline int VirtioGpuFrontendSnapshot::_internal_resources_size() const {
  return _internal_resources().size();
}
inline int VirtioGpuFrontendSnapshot::resources_size() const {
  return _internal_resources_size();
}
inline const ::google::protobuf::Map<::uint32_t, ::gfxstream::host::snapshot::VirtioGpuResourceSnapshot>& VirtioGpuFrontendSnapshot::_internal_resources() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.resources_.GetMap();
}
inline const ::google::protobuf::Map<::uint32_t, ::gfxstream::host::snapshot::VirtioGpuResourceSnapshot>& VirtioGpuFrontendSnapshot::resources() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:gfxstream.host.snapshot.VirtioGpuFrontendSnapshot.resources)
  return _internal_resources();
}
inline ::google::protobuf::Map<::uint32_t, ::gfxstream::host::snapshot::VirtioGpuResourceSnapshot>* PROTOBUF_NONNULL VirtioGpuFrontendSnapshot::_internal_mutable_resources() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.resources_.MutableMap();
}
inline ::google::protobuf::Map<::uint32_t, ::gfxstream::host::snapshot::VirtioGpuResourceSnapshot>* PROTOBUF_NONNULL VirtioGpuFrontendSnapshot::mutable_resources()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_mutable_map:gfxstream.host.snapshot.VirtioGpuFrontendSnapshot.resources)
  return _internal_mutable_resources();
}

// optional .gfxstream.host.snapshot.VirtioGpuTimelinesSnapshot timelines = 3;
inline bool VirtioGpuFrontendSnapshot::has_timelines() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.timelines_ != nullptr);
  return value;
}
inline const ::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot& VirtioGpuFrontendSnapshot::_internal_timelines() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot* p = _impl_.timelines_;
  return p != nullptr ? *p : *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot>(&::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot_globals_);
}
inline const ::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot& VirtioGpuFrontendSnapshot::timelines() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:gfxstream.host.snapshot.VirtioGpuFrontendSnapshot.timelines)
  return _internal_timelines();
}
inline void VirtioGpuFrontendSnapshot::unsafe_arena_set_allocated_timelines(
    ::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timelines_);
  }
  _impl_.timelines_ = reinterpret_cast<::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gfxstream.host.snapshot.VirtioGpuFrontendSnapshot.timelines)
}
inline ::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot* PROTOBUF_NULLABLE VirtioGpuFrontendSnapshot::release_timelines() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot* released = _impl_.timelines_;
  _impl_.timelines_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot* PROTOBUF_NULLABLE VirtioGpuFrontendSnapshot::unsafe_arena_release_timelines() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:gfxstream.host.snapshot.VirtioGpuFrontendSnapshot.timelines)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot* temp = _impl_.timelines_;
  _impl_.timelines_ = nullptr;
  return temp;
}
inline ::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot* PROTOBUF_NONNULL VirtioGpuFrontendSnapshot::_internal_mutable_timelines() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.timelines_ == nullptr) {
    auto* p = Super_::DefaultConstruct<::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot>(GetArena());
    _impl_.timelines_ = reinterpret_cast<::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot*>(p);
  }
  return _impl_.timelines_;
}
inline ::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot* PROTOBUF_NONNULL VirtioGpuFrontendSnapshot::mutable_timelines()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot* _msg = _internal_mutable_timelines();
  // @@protoc_insertion_point(field_mutable:gfxstream.host.snapshot.VirtioGpuFrontendSnapshot.timelines)
  return _msg;
}
inline void VirtioGpuFrontendSnapshot::set_allocated_timelines(::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timelines_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.timelines_ = reinterpret_cast<::gfxstream::host::snapshot::VirtioGpuTimelinesSnapshot*>(value);
  // @@protoc_insertion_point(field_set_allocated:gfxstream.host.snapshot.VirtioGpuFrontendSnapshot.timelines)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace snapshot
}  // namespace host
}  // namespace gfxstream


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // virtio_5fgpu_5ffrontend_5fsnapshot_2eproto_2epb_2eh
